version: '3.8'

services:
  postgres:
    container_name: 'TestTaskContainer'
    hostname: TestTask
    image: postgres
    ports: ["5431:5432"]
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=TestTask
    networks:
      - my-network
networks:
  my-network:
    name: existing_docker_network
    driver: bridge